"""
train.py
--------
Supervised training loop that uses pseudo-labels generated by the 
co-segmentation clustering pipeline to train a U-Net model.
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm
import cv2

# Import existing pipeline components
from demo import make_synthetic_scan
from pipeline import MedicalCoSegPipeline

# Import new components
from medical_coseg.unet import UNet
from medical_coseg.dataset import CoSegDataset

def generate_pseudo_labels(n_scans=10, n_clusters=5):
    print(f"Generating {n_scans} synthetic images...")
    bgr_arrays = [make_synthetic_scan(256, 256, seed=i) for i in range(n_scans)]

    print("Running Co-Segmentation Pipeline to generate pseudo-labels...")
    pipeline = MedicalCoSegPipeline(
        n_clusters=n_clusters,
        target_size=(224, 224),
        feature_size=(56, 56),
        use_pca=True,
        output_dir="outputs",
        use_gpu=torch.cuda.is_available()
    )
    
    # Run the core pipeline
    results = pipeline.run_on_arrays(bgr_arrays)
    
    originals = results["originals"] # list of (224, 224, 3) BGR images
    label_maps = results["label_maps"] # shape: (N, 56, 56) int32
    
    # Apply morphological cleaning to the label maps before training
    cleaned_label_maps = []
    for lm in label_maps:
        # Resize to 224x224 before cleaning to match training size
        lm_resized = cv2.resize(lm.astype('uint8'), (224, 224), interpolation=cv2.INTER_NEAREST).astype('int32')
        cleaned = pipeline.postprocessor.clean_label_map(lm_resized)
        cleaned_label_maps.append(cleaned)
        
    return originals, cleaned_label_maps

def train_unet(originals, masks, n_classes=5, epochs=10, batch_size=2):
    print("\nStarting U-Net Training...")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    dataset = CoSegDataset(originals, masks, target_size=(224, 224))
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    
    model = UNet(n_channels=3, n_classes=n_classes).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0
        
        # Use tqdm for a nice progress bar
        pbar = tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}")
        for imgs, true_masks in pbar:
            imgs = imgs.to(device)
            true_masks = true_masks.to(device)
            
            optimizer.zero_grad()
            
            logits = model(imgs)
            loss = criterion(logits, true_masks)
            
            loss.backward()
            optimizer.step()
            
            epoch_loss += loss.item()
            pbar.set_postfix({'loss': loss.item()})
            
        print(f"Epoch {epoch+1} Average Loss: {epoch_loss / len(dataloader):.4f}")
        
    os.makedirs("outputs", exist_ok=True)
    torch.save(model.state_dict(), "outputs/unet_weights.pth")
    print("\nTraining complete! Weights saved to outputs/unet_weights.pth")

if __name__ == "__main__":
    n_clusters = 5
    originals, masks = generate_pseudo_labels(n_scans=10, n_clusters=n_clusters)
    train_unet(originals, masks, n_classes=n_clusters, epochs=5)
